source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'AmahiAnywhere' do

use_frameworks!

    pod 'Alamofire', '~> 4.5'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'EVReflection/Alamofire'
    pod 'IQKeyboardManagerSwift'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'MobileVLCKit'
    pod 'Lightbox'
    pod 'ReachabilitySwift'
end
