source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'AmahiAnywhere' do

use_frameworks!

    pod 'Alamofire'
    pod 'MBProgressHUD'
    pod 'EVReflection/Alamofire', '~> 5.10.1'
    pod 'IQKeyboardManagerSwift'
    pod 'SkyFloatingLabelTextField'
    pod 'MobileVLCKit'
    pod 'Lightbox'
    pod 'ReachabilitySwift'
end
