source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'AmahiAnywhere' do

use_frameworks!

    pod 'Alamofire', '~> 4.7'
    pod 'MBProgressHUD'
    pod 'EVReflection/Alamofire'
    pod 'IQKeyboardManagerSwift'
    pod 'SkyFloatingLabelTextField'
    pod 'MobileVLCKit'
    pod 'Lightbox'
    pod 'ReachabilitySwift'
    pod 'SDWebImage'
    pod 'SwipeCellKit'
    pod 'google-cast-sdk'
    pod 'Floaty'
    
end